import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  // Avoid using next/font/google during local builds (can fail when offline).
  // Use system fonts / CSS in globals.css instead.
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {children}
      </body>
    </html>
  )
}
